{
  "hash": "5d73506cb851fc95dbf1a49601f24896",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tren Suhu Planet Bumi\"\ndescription: |\n  Bagaimana tren suhu planet bumi dari tahun ke tahun? Artikel ini mendemonstrasikan bagaimana mengimpor data tentang perubahan iklim dari sebuah situs web, mengolahnya, dan memvisualisasikannya ke dalam diagram garis. Proses seperti ini dapat diterapkan dalam menyusun desain pembelajaran Matematika yang ramah akan peserta didik dan relevan terhadap isu-isu penting planet bumi.\nauthor:\n  - name: Yosep Dwi Kristanto\n    url: https://people.usd.ac.id/~ydkristanto/\n    affiliation: Pendidikan Matematika, Universitas Sanata Dharma, Yogyakarta\n    affiliation-url: https://www.usd.ac.id/s1pmat\n    orcid: 0000-0003-1446-0422\ndate: 2024-07-31\ncategories:\n  - matematika membumi\n  - pendidikan\n  - perubahan iklim\n  - tutorial\nimage: \"anomali-suhu.png\"\nimage-alt: |\n  Tren anomali suhu planet bumi dari 1880 sampai 2024. Anomali suhu tersebut dihitung dengan garis dasar (baseline) rerata suhu pada periode 1951 - 1980. Secara umum, tren anomali suhu tersebut naik dari tahun ke tahun.\nkeywords: \n  - anomali suhu\n  - perubahan iklim\n  - pemanasan global\n  - tidyverse\n  - visualisasi data\n  - diagram garis\n  - Tujuan Pembangunan Berkelanjutan\ncopyright: \"© 2024 Yosep Dwi Kristanto\"\nlicense: \"CC BY\"\ngoogle-scholar: true\neditor_options: \n  chunk_output_type: console\n---\n\n\nBeberapa waktu lalu aku mendiskusikan ide Matematika Membumi. Diskusi dalam [webinar YPMIPA](https://www.instagram.com/p/C8848fQSZzw/){.external target=\"_blank\"} tersebut membahas sebuah desain pembelajaran yang menggunakan data riil, yaitu data tren suhu global planet bumi dari tahun ke tahun.\n\nIde seperti itu sebenarnya sudah aku pikirkan dan implementasikan kurang lebih pada tahun 2019. Pada tahun itu, aku mencoba mengajak para mahasiswa calon pendidik matematika tak hanya untuk bermatematika saja, tetapi juga memiliki kesadaran akan pembangunan berkelanjutan. Keseruannya dapat dilihat pada pos media sosial berikut.\n\n\n```{=html}\n<p align=\"center\">\n<iframe src=\"https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2FYosepDwiK%2Fposts%2Fpfbid02LvJ8WGjnXLe6SWTiBLNnTECkNXNAD6YtihSev81SbP8YfXdwd1mmSBoem2g1hVZ5l&show_text=true&width=500\" width=\"500\" height=\"601\" style=\"border:none;overflow:hidden\" scrolling=\"no\" frameborder=\"0\" allowfullscreen=\"true\" allow=\"autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share\"></iframe>\n</p>\n```\n\nDi artikel ini, kita tidak akan membahas desain pembelajaran tersebut. Melainkan, kita akan mengetahui bagaimana mendapatkan data tren suhu planet bumi tersebut, mengolahnya, dan memvisualisasikannya. Seluruh proses ini akan kita lakukan dengan menggunakan [R](https://www.R-project.org/){.external target=\"_blank\"}.\n\n## Data Tren Suhu Global {#sec-impor-data}\n\nBanyak situs web yang menyediakan data tren suhu global. Salah satunya adalah [GISTEMP](https://data.giss.nasa.gov/gistemp/){.external target=\"_blank\"}. Dari situs web itu, kita memilih data gabungan antara anomali suhu udara daratan dan anomali suhu air lautan. Apa itu anomali suhu? [Anomali suhu](https://www.ncei.noaa.gov/access/monitoring/dyk/anomalies-vs-temperature/){.external target=\"_blank\"} merupakan selisih terhadap suhu rata-rata atau garis dasar. Di situs GISTEMP, garis dasar yang digunakan adalah rata-rata suhu pada periode 1951 - 1980.\n\nLangkah awal sebelum kita melakukan proses berikutnya adalah memanggil paket [{tidyverse}](https://doi.org/10.32614/CRAN.package.tidyverse){.external target=\"_blank\"}. Paket tersebut menyediakan berbagai macam fungsi yang akan kita gunakan untuk mencapai tujuan kita.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse)\n```\n:::\n\n\nTak perlu berlama-lama, mari kita impor data tersebut dengan fungsi `read_csv()` dari paket {tidyverse}. Alamat fail yang akan kita impor adalah `https://data.giss.nasa.gov/gistemp/tabledata_v4/GLB.Ts+dSST.csv`. Baris pertama dalam fail tersebut merupakan keterangan \"*Land-Ocean: Global Means*\". Dengan demikian, kita perlu menambahkan argumen `skip = 1` dalam fungsi `read_csv()` agar data kita tidak memuat baris tersebut. Fail tersebut juga menggunakan simbol \\*\\*\\* sebagai penanda NA. Untuk itu, kita juga perlu menambahkan argumen `na = \"***\"` ke dalam fungsi tersebut. Kita namai data kita tersebut dengan `tren_suhu_global`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ntren_suhu_global <- read_csv(\n  \"https://data.giss.nasa.gov/gistemp/tabledata_v4/GLB.Ts+dSST.csv\",\n  skip = 1,\n  na = \"***\"\n)\n```\n:::\n\n\nSekarang kita memiliki data `tren_suhu_global`. Untuk melihat beberapa baris awal data tersebut, kita dapat menggunakan fungsi `head()`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nhead(tren_suhu_global)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 19\n   Year   Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec\n  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n1  1880 -0.19 -0.24 -0.09 -0.16 -0.1  -0.21 -0.18 -0.1  -0.14 -0.23 -0.21 -0.18\n2  1881 -0.2  -0.14  0.03  0.05  0.06 -0.19  0    -0.04 -0.16 -0.22 -0.18 -0.07\n3  1882  0.16  0.13  0.04 -0.17 -0.14 -0.23 -0.17 -0.07 -0.14 -0.24 -0.17 -0.36\n4  1883 -0.29 -0.37 -0.12 -0.18 -0.17 -0.08 -0.07 -0.14 -0.21 -0.11 -0.23 -0.11\n5  1884 -0.13 -0.08 -0.36 -0.4  -0.34 -0.35 -0.31 -0.28 -0.27 -0.25 -0.34 -0.31\n6  1885 -0.59 -0.34 -0.27 -0.42 -0.45 -0.44 -0.34 -0.32 -0.29 -0.24 -0.24 -0.1 \n# ℹ 6 more variables: `J-D` <dbl>, `D-N` <dbl>, DJF <dbl>, MAM <dbl>,\n#   JJA <dbl>, SON <dbl>\n```\n\n\n:::\n:::\n\n\nKita juga dapat menggunakan fungsi `glimpse()` dari {tidyverse} untuk melihat gambaran umum dari data tersebut.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nglimpse(tren_suhu_global)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 145\nColumns: 19\n$ Year  <dbl> 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890…\n$ Jan   <dbl> -0.19, -0.20, 0.16, -0.29, -0.13, -0.59, -0.44, -0.72, -0.34, -0…\n$ Feb   <dbl> -0.24, -0.14, 0.13, -0.37, -0.08, -0.34, -0.51, -0.57, -0.36, 0.…\n$ Mar   <dbl> -0.09, 0.03, 0.04, -0.12, -0.36, -0.27, -0.43, -0.36, -0.41, 0.0…\n$ Apr   <dbl> -0.16, 0.05, -0.17, -0.18, -0.40, -0.42, -0.28, -0.35, -0.20, 0.…\n$ May   <dbl> -0.10, 0.06, -0.14, -0.17, -0.34, -0.45, -0.25, -0.31, -0.22, -0…\n$ Jun   <dbl> -0.21, -0.19, -0.23, -0.08, -0.35, -0.44, -0.35, -0.25, -0.17, -…\n$ Jul   <dbl> -0.18, 0.00, -0.17, -0.07, -0.31, -0.34, -0.18, -0.26, -0.11, -0…\n$ Aug   <dbl> -0.10, -0.04, -0.07, -0.14, -0.28, -0.32, -0.31, -0.36, -0.16, -…\n$ Sep   <dbl> -0.14, -0.16, -0.14, -0.21, -0.27, -0.29, -0.24, -0.26, -0.12, -…\n$ Oct   <dbl> -0.23, -0.22, -0.24, -0.11, -0.25, -0.24, -0.28, -0.36, 0.01, -0…\n$ Nov   <dbl> -0.21, -0.18, -0.17, -0.23, -0.34, -0.24, -0.28, -0.27, 0.03, -0…\n$ Dec   <dbl> -0.18, -0.07, -0.36, -0.11, -0.31, -0.10, -0.26, -0.33, -0.04, -…\n$ `J-D` <dbl> -0.17, -0.09, -0.11, -0.18, -0.29, -0.34, -0.32, -0.37, -0.18, -…\n$ `D-N` <dbl> NA, -0.10, -0.09, -0.20, -0.27, -0.35, -0.30, -0.36, -0.20, -0.0…\n$ DJF   <dbl> NA, -0.17, 0.07, -0.34, -0.11, -0.41, -0.35, -0.52, -0.35, 0.01,…\n$ MAM   <dbl> -0.12, 0.05, -0.09, -0.16, -0.37, -0.38, -0.32, -0.34, -0.28, 0.…\n$ JJA   <dbl> -0.16, -0.08, -0.16, -0.10, -0.32, -0.37, -0.28, -0.29, -0.15, -…\n$ SON   <dbl> -0.19, -0.19, -0.18, -0.19, -0.29, -0.25, -0.27, -0.29, -0.03, -…\n```\n\n\n:::\n:::\n\n\nDari luaran fungsi tersebut, kita dapat melihat bahwa data kita memuat 145 baris dan 19 kolom. Informasi ini berguna untuk proses berikutnya.\n\n## Bergulat dengan Data {#sec-gulat-data}\n\nGulat tidak hanya dilombakan di olimpiade [#Paris2024](https://twitter.com/hashtag/Paris2024){.external target=\"_blank\"}, tetapi juga umum dilakukan terhadap data. Sekarang kita akan bergulat dengan data. Seperti olahraga gulat yang menantang, bergulat dengan data juga tak kalah menantang. Akan tetapi, tantangan itu akan menghasilkan data yang rapi. Kita lakukan pergulatan ini setahap demi setahap.\n\nKetika kita menggunakan fungsi `glimpse()` sebelumnya, kita tahu bahwa data kita memuat 19 kolom. Kolom yang akan kita olah di sini adalah 13 kolom pertama. Untuk itu, pada tahap pertama, kita gunakan fungsi `select()` dari {tidyverse} untuk memilih ketigabelas kolom tersebut. Kita juga dapat mengganti nama kolom pertama yang awalnya `Year` menjadi `tahun` dengan menggunakan `rename()` dari {tidyverse}. Untuk melihat hasilnya kita dapat menggunakan fungsi `head()` lagi.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ntren_suhu_global <- tren_suhu_global |> \n  select(1:13) |> \n  rename(tahun = Year)\n\nhead(tren_suhu_global)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 13\n  tahun   Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec\n  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n1  1880 -0.19 -0.24 -0.09 -0.16 -0.1  -0.21 -0.18 -0.1  -0.14 -0.23 -0.21 -0.18\n2  1881 -0.2  -0.14  0.03  0.05  0.06 -0.19  0    -0.04 -0.16 -0.22 -0.18 -0.07\n3  1882  0.16  0.13  0.04 -0.17 -0.14 -0.23 -0.17 -0.07 -0.14 -0.24 -0.17 -0.36\n4  1883 -0.29 -0.37 -0.12 -0.18 -0.17 -0.08 -0.07 -0.14 -0.21 -0.11 -0.23 -0.11\n5  1884 -0.13 -0.08 -0.36 -0.4  -0.34 -0.35 -0.31 -0.28 -0.27 -0.25 -0.34 -0.31\n6  1885 -0.59 -0.34 -0.27 -0.42 -0.45 -0.44 -0.34 -0.32 -0.29 -0.24 -0.24 -0.1 \n```\n\n\n:::\n:::\n\n\nSekarang kita mendapatkan data yang memuat 13 kolom. Kolom pertama merupakan tahun, kolom kedua sampai ketiga belas merupakan bulan Januari sampai Desember. Isi sel kolom kedua sampai ketigabelas merupakan anomali suhu.\n\nSampai di sini, aku teringat terhadap salah satu adegan di sebuah serial TV yang berjudul [Friends](https://www.imdb.com/title/tt0108778/){.external target=\"_blank\"}. Dalam episode yang berjudul \"*The One with the Cop*\", Ross meminta Chandler untuk mem-*pivot* sofa yang mereka angkat.\n\n\n```{=html}\n<p align=\"center\">\n<iframe src=\"https://giphy.com/embed/2OP9jbHFlFPW\" width=\"480\" height=\"307\" style=\"\" frameBorder=\"0\" class=\"giphy-embed\" allowFullScreen></iframe>\n</p>\n```\n\nPerintah Ross tersebut juga dapat diterapkan terhadap data kita. Kita dapat mem-*pivot* (memutar) data kita dengan menggunakan fungsi `pivot_longer()`. Dengan fungsi tersebut, data kita yang awalnya melebar akan berubah bentuknya menjadi data yang memanjang. Oleh karena itu, di tahap kedua, kita perlu memutar data kita agar menjadi data yang memanjang.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ntren_suhu_global <- tren_suhu_global |> \n  pivot_longer(\n    cols = 2:13,\n    names_to = \"bulan\",\n    values_to = \"anomali_suhu\"\n  )\n\nhead(tren_suhu_global)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  tahun bulan anomali_suhu\n  <dbl> <chr>        <dbl>\n1  1880 Jan          -0.19\n2  1880 Feb          -0.24\n3  1880 Mar          -0.09\n4  1880 Apr          -0.16\n5  1880 May          -0.1 \n6  1880 Jun          -0.21\n```\n\n\n:::\n:::\n\n\nMengapa kita memerlukan data yang memanjang? Data memanjang tersebut akan memudahkan kita untuk mengolahnya pada tahapan berikutnya.\n\nTahap ketiga, kita perlu menggabungkan nilai sel dalam kolom pertama dan kedua untuk membuat sebuah kolom baru, yaitu `tanggal`, yang formatnya *Date*.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\npemetaan_bulan <- c(\n  \"Jan\" = \"01\",\n  \"Feb\" = \"02\",\n  \"Mar\" = \"03\",\n  \"Apr\" = \"04\",\n  \"May\" = \"05\",\n  \"Jun\" = \"06\",\n  \"Jul\" = \"07\",\n  \"Aug\" = \"08\",\n  \"Sep\" = \"09\",\n  \"Oct\" = \"10\",\n  \"Nov\" = \"11\",\n  \"Dec\" = \"12\"\n)\n\ntren_suhu_global <- tren_suhu_global |> \n  mutate(\n    tanggal = as.Date(\n      paste(tahun, pemetaan_bulan[bulan], \"01\", sep = \"-\")\n    )\n  )\n\nhead(tren_suhu_global)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  tahun bulan anomali_suhu tanggal   \n  <dbl> <chr>        <dbl> <date>    \n1  1880 Jan          -0.19 1880-01-01\n2  1880 Feb          -0.24 1880-02-01\n3  1880 Mar          -0.09 1880-03-01\n4  1880 Apr          -0.16 1880-04-01\n5  1880 May          -0.1  1880-05-01\n6  1880 Jun          -0.21 1880-06-01\n```\n\n\n:::\n:::\n\n\nKarena kolom `tahun` dan `bulan` sudah diwakili oleh kolom `tanggal`, kita dapat mengabaikan kedua kolom tersebut.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ntren_suhu_global <- tren_suhu_global |> \n  select(tanggal, anomali_suhu)\n\nhead(tren_suhu_global)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  tanggal    anomali_suhu\n  <date>            <dbl>\n1 1880-01-01        -0.19\n2 1880-02-01        -0.24\n3 1880-03-01        -0.09\n4 1880-04-01        -0.16\n5 1880-05-01        -0.1 \n6 1880-06-01        -0.21\n```\n\n\n:::\n:::\n\n\n*Nah*, sekarang kita mendapatkan data yang rapi. Data kita sekarang hanya memuat dua variabel, yaitu `tanggal` dan `anomali_suhu`. Selanjutnya kita akan memvisualisasikan `anomali_suhu` setiap `tanggal`-nya.\n\n## Visualisasi Data {#sec-visualisasi-data}\n\nData yang rapi yang sudah di tangan. Selanjutnya, kita visualisasikan data tersebut ke dalam diagram garis untuk melihat tren `anomali_suhu` setiap `tanggal`-nya. Untuk melakukannya, kita dapat menggunakan fungsi `ggplot()` dan peranakannya. Hasilnya disajikan pada @fig-diagram-garis-v1.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"false\"}\ndiagram_garis <- tren_suhu_global |> \n  ggplot(aes(x = tanggal, y = anomali_suhu)) + \n  geom_line()\n\nprint(diagram_garis)\n```\n\n::: {.cell-output-display}\n![Tren `anomali_suhu` setiap `tanggal`-nya.](index_files/figure-html/fig-diagram-garis-v1-1.png){#fig-diagram-garis-v1 fig-align='center' width=672}\n:::\n:::\n\n\nDiagram pada @fig-diagram-garis-v1 dapat kita modifikasi. Misalnya, kita dapat mengubah judul sumbu-*x* dan *y* pada diagram tersebut. Kita juga dapat mengubah warna garis serta memberikan judul, anak judul, dan takarir pada diagram tersebut. Sentuhan terakhir, kita dapat memilih tema `theme_minimal()` dan menambahkan pola tren tersebut dengan `geom_smooth()`. Hasilnya ditunjukkan pada @fig-diagram-garis-v2.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"false\"}\ndiagram_garis + \n  geom_line(color = \"#427D9D\") + \n  geom_smooth(\n    method = \"gam\",\n    formula = y ~ s(x, bs = \"cs\"),\n    color = \"#164863\"\n  ) + \n  theme_minimal() + \n  labs(\n    title = \"Tren Anomali Suhu Setiap Waktunya\",\n    subtitle = \"Anomali suhu relatif terhadap rerata suhu pada 1951 - 1980\",\n    x = \"Waktu\",\n    y = \"Anomali Suhu (°C)\",\n    caption = \"Data: GISTEMP\"\n  )\n```\n\n::: {.cell-output-display}\n![Tren `anomali_suhu` setiap `tanggal`-nya yang sudah diperbaiki.](index_files/figure-html/fig-diagram-garis-v2-1.png){#fig-diagram-garis-v2 fig-align='center' width=672}\n:::\n:::\n\n\n## Catatan Akhir\n\nKita telah memvisualisasikan tren suhu planet bumi dari tahun ke tahun, yaitu mulai 1880 sampai 2024. Untuk mendapatkan visualisasi pada @fig-diagram-garis-v2, pertama kita impor data dari situs web GISTEMP. Hal ini telah dipaparkan pada @sec-impor-data. Kedua, kita telah bergulat dengan data tersebut pada @sec-gulat-data untuk mendapatkan data yang rapi. Ketiga, data yang rapi tersebut selanjutnya kita gunakan untuk memvisualisasikan tren suhu planet bumi setiap waktunya pada @sec-visualisasi-data.\n\nProses yang didemonstrasikan pada artikel ini dapat digunakan untuk menyusun desain pembelajaran Matematika yang menggunakan data riil, khususnya data tentang tema perubahan iklim. Penggunaan data perubahan iklim tersebut tidak hanya dapat memupuk kesadaran peserta didik akan isu planet bumi yang ditinggalinya, tetapi juga memudahkan mereka untuk bermatematika menggunakan konteks di sekitarnya.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}